site_name: Textualize

nav:

  - projects.md
  - about-us.md
  - why-i-founded-textualize.md
  

markdown_extensions:
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  # - pymdownx.superfences
  - attr_list
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      baselevel: 1

theme:
  name: material
  custom_dir: docs/custom_theme

  # features:
  #   - navigation.tabs
  #   - navigation.indexes
  #   - navigation.tabs.sticky
  #   - navigation.footer
  #   - content.code.annotate
  #   - content.code.copy

  features:
    - navigation.expand
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky


  palette:

    
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


extra_css:
  - stylesheets/custom.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/textualizeio
      name: Textualize on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/textualize/textual/
      name: Textual on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Enf6Z3qhVr
      name: Textual Discord server
